import { AppParams } from "./types";

export const defaultParams: AppParams = {
  recursionDepth: 4,
  baseSize: 8,
  pyramidHeight: 13.5,
  seed: 1841919,
  symmetryMode: true,
  capBase: true,
  splitRatio: 0.47,
  kochAngle: 38,
  normalExtrusion: 0.34,
  verticalBias: 1.25,
  buttressBias: 0.2,
  centralLift: 0.44,
  centralSpireBias: 1.9,
  centralButtressBias: 0.25,
  levelDecay: 0.54,
  randomness: 0.18,
  angleJitter: 0,
  heightJitter: 0,
  splitJitter: 0,
  asymmetry: 0,
  gothicVerticality: 2.2,
  spireTaper: 0.45,
  ridgeSharpness: 0.86,
  buttressSpread: 0.5,
  axisAttractorStrength: 0.7,
  radialClusterStrength: 0.14,
  terraceQuantization: 0,
  verticalCoherence: 0.86,
  shellClosure: 0.82,
  branchAngleLimit: 20,
  triangulationMode: "spireFan",
  smoothNormals: false,
  doubleSidedMaterial: true,
  wireframe: false,
  showEdges: true,
  showAxes: false,
  maxTriangles: 250000,
  materialMode: "matte white",
  background: "dark gray",
  ambientLightIntensity: 0.65,
  directionalLightIntensity: 2.35,
  autoRotate: false,
  cameraMode: "perspective"
};

export const presets: Record<string, Partial<AppParams>> = {
  "Screenshot Target": {
    seed: 1841919,
    recursionDepth: 4,
    baseSize: 8,
    pyramidHeight: 13.5,
    symmetryMode: true,
    splitRatio: 0.47,
    normalExtrusion: 0.34,
    verticalBias: 1.25,
    centralLift: 0.44,
    centralSpireBias: 1.9,
    levelDecay: 0.54,
    randomness: 0.18,
    gothicVerticality: 2.2,
    spireTaper: 0.45,
    ridgeSharpness: 0.86,
    verticalCoherence: 0.86,
    shellClosure: 0.82,
    branchAngleLimit: 20,
    materialMode: "matte white",
    background: "dark gray",
    showEdges: true
  },
  "Needle Crown": {
    seed: 902101,
    recursionDepth: 4,
    pyramidHeight: 15.5,
    normalExtrusion: 0.24,
    centralSpireBias: 2.8,
    gothicVerticality: 2.8,
    verticalCoherence: 0.94,
    shellClosure: 0.9,
    branchAngleLimit: 14,
    randomness: 0.12,
    spireTaper: 0.72
  },
  "Heavy Shell": {
    seed: 512877,
    recursionDepth: 3,
    baseSize: 9.5,
    pyramidHeight: 12,
    normalExtrusion: 0.42,
    centralLift: 0.6,
    centralSpireBias: 1.2,
    shellClosure: 0.72,
    branchAngleLimit: 26,
    randomness: 0.24,
    buttressBias: 0.35
  },
  "Thin Blades": {
    seed: 744031,
    recursionDepth: 4,
    baseSize: 7,
    pyramidHeight: 14.5,
    splitRatio: 0.5,
    normalExtrusion: 0.28,
    centralSpireBias: 2.25,
    verticalCoherence: 0.92,
    shellClosure: 0.84,
    branchAngleLimit: 16,
    randomness: 0.22,
    ridgeSharpness: 1
  }
};

export function applyPreset(target: AppParams, name: string): void {
  Object.assign(target, presets[name]);
}
